/**
 * Adopts the UIScene lifecycle in the generated iOS project.
 *
 * iOS 27's UIKit hard-crashes (EXC_BREAKPOINT in
 * `_UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption`) any app
 * that never connects a UIScene. Expo 57's AppDelegate template still creates
 * its window straight from `didFinishLaunchingWithOptions`, the pre-Scenes
 * pattern, so a stock prebuild launches and dies. See HANDOVER.md
 * (2026-09-23) for the crash investigation.
 *
 * This used to be hand-edited into `ios/`, which is gitignored and
 * regenerated by every `expo prebuild` and every EAS build — meaning a store
 * build would ship the crash. As a config plugin it is reapplied each time.
 *
 * Four mods, matching the four hand edits:
 *  - writes ios/<name>/SceneDelegate.swift (window creation + startReactNative)
 *  - strips window creation out of AppDelegate and points iOS at that class
 *  - adds UIApplicationSceneManifest to Info.plist
 *  - registers SceneDelegate.swift in the Xcode project's Sources phase
 */
const fs = require('fs');
const path = require('path');
const {
  IOSConfig,
  withAppDelegate,
  withDangerousMod,
  withInfoPlist,
  withXcodeProject,
} = require('expo/config-plugins');

const SCENE_DELEGATE_FILE = 'SceneDelegate.swift';

const SCENE_DELEGATE_SOURCE = `import React
import UIKit

// Generated by plugins/withSceneDelegate.js — edit there, not here.
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
    guard let windowScene = scene as? UIWindowScene,
      let appDelegate = UIApplication.shared.delegate as? AppDelegate,
      let factory = appDelegate.reactNativeFactory
    else {
      return
    }

    let window = UIWindow(windowScene: windowScene)
    appDelegate.window = window
    self.window = window

    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: nil)
  }
}
`;

// The template's window creation, removed because SceneDelegate now owns it.
const WINDOW_CREATION =
  /#if os\(iOS\) \|\| os\(tvOS\)\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\s*factory\.startReactNative\([\s\S]*?\)\s*#endif[ \t]*\n(?:[ \t]*\n)?/;

const SCENE_CONFIGURATION_METHOD = `
  // UIScene lifecycle — see plugins/withSceneDelegate.js.
  public func application(
    _ application: UIApplication,
    configurationForConnecting connectingSceneSession: UISceneSession,
    options: UIScene.ConnectionOptions
  ) -> UISceneConfiguration {
    let configuration = UISceneConfiguration(
      name: "Default Configuration",
      sessionRole: connectingSceneSession.role)
    configuration.delegateClass = SceneDelegate.self
    return configuration
  }
`;

function withSceneDelegateFile(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const projectName = IOSConfig.XcodeUtils.getProjectName(config.modRequest.projectRoot);
      const target = path.join(config.modRequest.platformProjectRoot, projectName, SCENE_DELEGATE_FILE);
      fs.writeFileSync(target, SCENE_DELEGATE_SOURCE);
      return config;
    },
  ]);
}

function withSceneAppDelegate(config) {
  return withAppDelegate(config, (config) => {
    if (config.modResults.language !== 'swift') {
      throw new Error('withSceneDelegate: expected a Swift AppDelegate');
    }
    let contents = config.modResults.contents;
    if (contents.includes('configurationForConnecting')) {
      return config;
    }
    if (!WINDOW_CREATION.test(contents)) {
      // Fail the build loudly: silently skipping would ship the launch crash.
      throw new Error('withSceneDelegate: AppDelegate template changed — window creation block not found');
    }
    contents = contents.replace(WINDOW_CREATION, '');
    contents = contents.replace(/\n  \/\/ Linking API/, `${SCENE_CONFIGURATION_METHOD}\n  // Linking API`);
    if (!contents.includes('configurationForConnecting')) {
      throw new Error('withSceneDelegate: could not insert scene configuration method');
    }
    config.modResults.contents = contents;
    return config;
  });
}

function withSceneManifest(config) {
  return withInfoPlist(config, (config) => {
    config.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
          },
        ],
      },
    };
    return config;
  });
}

function withSceneDelegateInProject(config) {
  return withXcodeProject(config, (config) => {
    const projectName = IOSConfig.XcodeUtils.getProjectName(config.modRequest.projectRoot);
    const filepath = `${projectName}/${SCENE_DELEGATE_FILE}`;
    if (!config.modResults.hasFile(filepath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath,
        groupName: projectName,
        project: config.modResults,
      });
    }
    return config;
  });
}

module.exports = function withSceneDelegate(config) {
  config = withSceneDelegateFile(config);
  config = withSceneAppDelegate(config);
  config = withSceneManifest(config);
  config = withSceneDelegateInProject(config);
  return config;
};
